language: go
go:
  - 1.10.x
install:
  go get -u github.com/spf13/pflag
  go get -u golang.org/x/text/transform
  go get -u golang.org/x/text/encoding/simplifiedchinese
  go get -u github.com/google/btree

script:
  - go test